/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Model.User;
import Repositories.DBConnection;
import Repositories.DBQuery;
import java.awt.Dimension;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.time.LocalDate;
import javax.swing.JOptionPane;


/**
 *
 * @author Hyun
 */
public class HomeForm extends javax.swing.JFrame {

    /**
     * Creates new form HomeForm
     */
    DBConnection bConnection = new DBConnection();
    DBQuery bQuery = new DBQuery(bConnection);
    ArrayList<User> al = bQuery.getList();
    DefaultTableModel defaultTableModel = new DefaultTableModel();

    public HomeForm() {
        initComponents();
        loadData(al);
    }

    public void loadData(ArrayList<User> al) {
        defaultTableModel = (DefaultTableModel) tbluser.getModel();
        defaultTableModel.setRowCount(0);
        int id = 1;
        for (User user : al) {
            defaultTableModel.addRow(new Object[]{
                id,
                user.getFullName(),
                user.getUsername(),
                user.getPassword(),
                user.getEmail(),
                user.getBirthDate(),
                user.getIsActive() ? "Online" : "Offline"
            });
            id++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbluser = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtfullname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtbirth = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        rdtrue = new javax.swing.JRadioButton();
        rdfalse = new javax.swing.JRadioButton();
        lbimg = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        btninsert = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        jLabel6.setText("jLabel4");

        jTextField3.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 70, 950, 10);

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(210, 0, 20, 600);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sm-logo.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 50, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("POLYSCHOOL");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 20, 150, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("STUDENTS MANAGEMENT");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(400, 20, 350, 33);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn-logout-white.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(10, 290, 200, 70);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn-students.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(10, 80, 200, 70);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn-help-white.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(10, 150, 200, 70);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn-account-white.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(10, 220, 200, 70);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/closeimg.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(840, 10, 110, 50);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("ID:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 40));

        txtid.setEditable(false);
        txtid.setBackground(new java.awt.Color(204, 204, 204));
        txtid.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 160, -1));

        tbluser.setBackground(new java.awt.Color(255, 255, 255));
        tbluser.setForeground(new java.awt.Color(0, 0, 0));
        tbluser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Full name", "User name", "Password", "Email", "Birth date", "Active"
            }
        ));
        tbluser.setGridColor(new java.awt.Color(0, 0, 0));
        tbluser.setOpaque(false);
        tbluser.setSelectionBackground(new java.awt.Color(102, 102, 255));
        jScrollPane1.setViewportView(tbluser);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 650, 240));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Fullname:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 40));

        txtfullname.setBackground(new java.awt.Color(204, 204, 204));
        txtfullname.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtfullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 160, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Username:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 40));

        txtusername.setBackground(new java.awt.Color(204, 204, 204));
        txtusername.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 160, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Password:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, 40));

        txtpassword.setBackground(new java.awt.Color(204, 204, 204));
        txtpassword.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 160, -1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Email:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, 40));

        txtemail.setBackground(new java.awt.Color(204, 204, 204));
        txtemail.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 160, -1));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Birth date:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, 40));

        txtbirth.setBackground(new java.awt.Color(204, 204, 204));
        txtbirth.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtbirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 160, -1));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Is active:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 40));

        buttonGroup1.add(rdtrue);
        rdtrue.setForeground(new java.awt.Color(0, 0, 0));
        rdtrue.setText("Online");
        jPanel2.add(rdtrue, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        buttonGroup1.add(rdfalse);
        rdfalse.setForeground(new java.awt.Color(0, 0, 0));
        rdfalse.setText("Offline");
        jPanel2.add(rdfalse, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        lbimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/unknow-person-img.png"))); // NOI18N
        jPanel2.add(lbimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 850, 10));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn-reset.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, -1, -1));

        btninsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn-insert.png"))); // NOI18N
        btninsert.setBorder(null);
        btninsert.setContentAreaFilled(false);
        btninsert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btninsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsertActionPerformed(evt);
            }
        });
        jPanel2.add(btninsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn-delete.png"))); // NOI18N
        jButton8.setBorder(null);
        jButton8.setContentAreaFilled(false);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn-update.png"))); // NOI18N
        jButton9.setBorder(null);
        jButton9.setContentAreaFilled(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn-upload.png"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.setContentAreaFilled(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 130, -1));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(210, 70, 730, 500);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        LogoutFrame logoutFrame = new LogoutFrame();
        logoutFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btninsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsertActionPerformed
        // TODO add your handling code here:
        if (selectedImagePath == null || selectedImagePath.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please upload an image before inserting.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String fullName = txtfullname.getText();
        String userName = txtusername.getText();
        String password = txtpassword.getText();
        String email = txtemail.getText();
        Date birthDate = Date.valueOf(txtbirth.getText());
        Boolean isActive;
        if (rdtrue.isSelected()) {
            isActive = true;
        } else {
            isActive = false;
        }
        try {
            User u = new User(fullName, userName, password, email, birthDate, isActive);
            bQuery.insertUser(u);
            al.clear();
            al = bQuery.getList();
            loadData(al);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btninsertActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        lbimg.setPreferredSize(new Dimension(200, 100)); // Kích thước cố định 200x200
        lbimg.setSize(200, 100); // Áp dụng kích thước

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Select an image");
        int result = fileChooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String destinationPath = "C:\\Users\\Hyun\\Documents\\NetBeansProjects\\TestASMJava3\\src\\Images\\user-images\\" + selectedFile.getName();
            try {
                // Lưu ảnh vào thư mục
                Files.copy(selectedFile.toPath(), Paths.get(destinationPath), StandardCopyOption.REPLACE_EXISTING);
                System.out.println("Image saved: " + destinationPath);
                selectedImagePath = destinationPath;
                // Buộc JLabel cập nhật kích thước
                lbimg.revalidate();
                lbimg.repaint();

                // Kiểm tra kích thước JLabel
                if (lbimg.getWidth() > 0 && lbimg.getHeight() > 0) {
                    ImageIcon imageIcon = new ImageIcon(selectedFile.getAbsolutePath());
                    Image scaledImage = imageIcon.getImage().getScaledInstance(lbimg.getWidth(), lbimg.getHeight(), Image.SCALE_SMOOTH);
                    lbimg.setIcon(new ImageIcon(scaledImage));
                } else {
                    System.out.println("Warning: JLabel dimensions are not set properly.");
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        HelpForm form = new HelpForm();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        AccountFrame accountFrame = new AccountFrame();
        accountFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed
    private String selectedImagePath; // Đường dẫn ảnh được chọn

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btninsert;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lbimg;
    private javax.swing.JRadioButton rdfalse;
    private javax.swing.JRadioButton rdtrue;
    private javax.swing.JTable tbluser;
    private javax.swing.JTextField txtbirth;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfullname;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
